import { NextResponse } from 'next/server';

const vehicleData = {
  "Abarth": ["595 / 695", "124 Spider", "Punto Evo", "Grande Punto"],
  "AC": ["Cobra", "Ace", "Aceca", "3000ME", "Greyhound"],
  "Acura": ["NSX", "Integra", "Legend", "MDX", "RDX", "TLX"],
  "Alfa Romeo": ["Giulia", "Spider", "Stelvio", "GTV", "Alfasud", "156", "Giulietta", "8C Competizione", "Montreal", "33 Stradale"],
  "Alpine": ["A110", "A310", "A610", "GTA"],
  "Alvis": ["TD 21", "TE 21", "TF 21", "Speed 20", "Speed 25", "4.3 Litre", "Grey Lady"],
  "AMC": ["Javelin", "AMX", "Gremlin", "Pacer", "Eagle", "Hornet"],
  "Ariel": ["Atom", "Nomad", "Ace (motorcycle)", "Square Four (motorcycle)"],
  "Aston Martin": ["DB5", "Vantage", "DB9", "DBS", "DB11", "Vanquish", "DBX", "Lagonda", "Valkyrie", "One-77"],
  "Audi": ["Quattro", "A4", "A6", "TT", "R8", "A3", "Q7", "Q5", "RS2 Avant", "e-tron"],
  "Austin": ["Mini", "Seven", "A30/A35", "Allegro", "Metro", "Princess", "Ambassador", "Cambridge", "Westminster", "1100/1300"],
  "Austin-Healey": ["3000", "100", "Sprite", "100-6"],
  "Bentley": ["Continental GT", "Mulsanne", "Bentayga", "Arnage", "Flying Spur", "Blower Bentley", "R-Type Continental", "Brooklands", "Azure", "Turbo R"],
  "BMW": ["3 Series", "5 Series", "M3", "M5", "X5", "2002", "Z3/Z4", "i8", "7 Series", "E9 CSL"],
  "Bristol": ["400", "401", "405", "Blenheim", "Fighter", "Britannia"],
  "BSA": ["Gold Star", "Bantam", "A65", "Rocket 3", "M20"],
  "Bugatti": ["Veyron", "Chiron", "Type 57 Atlantic", "Type 35", "EB110", "Divo", "Centodieci", "La Voiture Noire"],
  "Buick": ["Riviera", "Regal", "Skylark", "Roadmaster", "GSX", "LeSabre", "Century", "Electra 225"],
  "Cadillac": ["Eldorado", "Escalade", "DeVille", "CTS-V", "Series 62", "Fleetwood", "CT5-V Blackwing", "Allanté", "Seville", "Sixteen"],
  "Caterham": ["Seven", "21", "SP/300.R"],
  "Chevrolet": ["Corvette", "Camaro", "Silverado", "Impala", "Bel Air", "Suburban", "Chevelle", "Tahoe", "Volt", "Monte Carlo"],
  "Chrysler": ["300", "Voyager / Town & Country", "New Yorker", "PT Cruiser", "Viper (under Dodge initially)", "Crossfire", "LeBaron", "Imperial"],
  "Citroen": ["DS", "2CV", "CX", "SM", "BX", "XM", "C4 Cactus", "GS", "Traction Avant", "HY Van"],
  "Dacia": ["Duster", "Sandero", "Logan", "Spring"],
  "Daf": ["600", "33", "44", "55", "66"],
  "Daihatsu": ["Copen", "Charade", "Terios", "Fourtrak", "Materia"],
  "Daimler": ["SP250 \"Dart\"", "Double Six", "Sovereign", "DS420 Limousine", "Conquest"],
  "Datsun": ["240Z", "510", "Bluebird", "Cherry", "Sunny", "120Y"],
  "De Tomaso": ["Pantera", "Mangusta", "Guarà", "Longchamp", "Deauville"],
  "Delage": ["D8", "D6", "DI"],
  "Delahaye": ["135", "175", "235"],
  "DeLorean": ["DMC-12"],
  "Dodge": ["Charger", "Challenger", "Viper", "Ram", "Durango", "Caravan", "Dart", "Coronet", "Daytona", "Omni"],
  "Ducati": ["Monster", "916", "Panigale", "Scrambler", "Multistrada", "Diavel", "Hypermotard", "SuperSport", "750 Imola Desmo", "851"],
  "Facel Vega": ["HK500", "Facel II", "Excellence", "Facellia"],
  "Ferrari": ["F40", "Testarossa", "250 GTO", "LaFerrari", "Enzo", "Dino 246 GT", "458 Italia", "F355", "Daytona", "288 GTO"],
  "Fiat": ["500", "Panda", "Uno", "124 Spider", "Punto", "Multipla", "Tipo", "X1/9", "126", "127"],
  "Ford": ["Mustang", "F-150", "Model T", "GT/GT40", "Focus", "Fiesta", "Explorer", "Bronco", "Thunderbird", "Escort"],
  "Ginetta": ["G4", "G12", "G15", "G40", "G55"],
  "GMC": ["Sierra", "Yukon", "Suburban", "Jimmy", "Syclone", "Typhoon", "Canyon", "Acadia"],
  "Harley-Davidson": ["Sportster", "Fat Boy", "Electra Glide", "Softail", "Road King", "Dyna Wide Glide", "V-Rod", "Knucklehead", "Panhead", "Shovelhead"],
  "Hillman": ["Imp", "Avenger", "Hunter", "Minx"],
  "Honda": ["Civic", "Accord", "NSX", "CR-V", "S2000", "Prelude", "Integra", "CB750 (Motorcycle)", "Super Cub (Motorcycle)", "Gold Wing (Motorcycle)"],
  "Humber": ["Sceptre", "Super Snipe", "Hawk", "Imperial"],
  "Hyundai": ["i30", "Tucson", "Santa Fe", "Genesis Coupe", "i10", "i20", "Kona", "Ioniq 5"],
  "Indian": ["Chief", "Scout", "FTR", "Chieftain", "Springfield", "Roadmaster"],
  "Infiniti": ["Q50", "G35/G37", "QX80", "FX35/FX50", "QX60"],
  "Isuzu": ["Trooper", "D-Max", "Piazza", "Vehicross", "Bellett"],
  "Jaguar": ["E-Type", "XJ", "F-Type", "XKSS/D-Type", "Mark II", "XJ220", "F-Pace", "XF", "XK8/XKR", "I-Pace"],
  "Jeep": ["Wrangler", "Cherokee/Grand Cherokee", "Willys MB", "Gladiator", "Wagoneer", "Compass", "Renegade", "Commander"],
  "Jensen": ["Interceptor", "Healey", "541R", "CV8"],
  "Kawasaki": ["Ninja", "Z1", "H2", "Vulcan", "KLR650", "Versys", "KX Series", "Concours"],
  "Kia": ["Sportage", "Sorento", "Stinger", "Ceed", "Telluride", "EV6", "Soul", "Rio"],
  "Lada": ["Niva", "Riva/VAZ-2105", "Samara", "Classic/VAZ-2101"],
  "Lamborghini": ["Countach", "Miura", "Diablo", "Aventador", "Huracán", "Gallardo", "Murciélago", "Urus", "LM002", "Veneno"],
  "Lancia": ["Stratos", "Delta", "Fulvia", "Aurelia", "Beta", "Thema", "037 Stradale", "Flaminia", "Appia", "Gamma"],
  "Land Rover": ["Defender", "Range Rover", "Discovery", "Range Rover Sport", "Freelander", "Evoque", "Velar", "Series I/II/III"],
  "Lexus": ["LS 400", "LFA", "IS", "RX", "GS", "ES", "SC 400", "GX", "LX", "LC 500"],
  "Lincoln": ["Continental", "Navigator", "Town Car", "Mark Series", "Aviator", "Zephyr"],
  "Lotus": ["Elan", "Esprit", "Elise", "Exige", "Evora", "Europa", "Elite", "Emira", "Carlton", "Evija"],
  "Maserati": ["Ghibli", "Quattroporte", "GranTurismo", "MC20", "3500 GT", "Merak", "Bora", "Levante", "Shamal", "Biturbo"],
  "Mazda": ["MX-5/Miata", "RX-7", "RX-8", "3", "6", "CX-5", "Cosmo", "323F", "CX-30", "MX-30"],
  "McLaren": ["F1", "P1", "720S", "Senna", "650S", "570S", "Artura", "MP4-12C", "GT", "Speedtail"],
  "Mercedes-Benz": ["300 SL", "S-Class", "E-Class", "G-Class", "C-Class", "SL-Class", "AMG GT", "CLK GTR", "SLS AMG", "190E"],
  "MG": ["MGB", "Midget", "MGA", "TC/TD/TF", "F/TF", "ZS", "HS", "Metro", "Maestro", "Montego"],
  "Mini": ["Cooper (Classic)", "Cooper (BMW)", "Countryman", "Clubman", "John Cooper Works", "Moke"],
  "Mitsubishi": ["Lancer Evolution", "Pajero/Shogun", "GTO/3000GT", "Eclipse", "Galant", "Colt", "Outlander", "Starion", "i-MiEV", "Delica"],
  "Morgan": ["Plus 4", "Plus 8", "3-Wheeler", "Aero 8", "4/4", "Roadster"],
  "Morris": ["Minor", "Oxford", "Eight", "Marina", "Ital", "Cowley"],
  "Moto Guzzi": ["V7", "Le Mans", "California", "Griso", "Norge", "Stelvio", "Daytona"],
  "MV Agusta": ["F4", "Brutale", "750 Sport America", "Superveloce", "Turismo Veloce", "Dragster"],
  "Nissan": ["GT-R", "Z-Series (Fairlady)", "Skyline", "Patrol", "Qashqai", "Juke", "Micra", "Titan", "Leaf", "Silvia/200SX"],
  "Noble": ["M600", "M12", "M400"],
  "Norton": ["Commando", "Manx", "Dominator", "International", "V4SV", "Atlas"],
  "Opel": ["Manta", "Kadett", "Corsa", "Astra", "Vectra", "Insignia", "GT", "Ascona", "Calibra", "Rekord"],
  "Pagani": ["Zonda", "Huayra"],
  "Peugeot": ["205", "405", "504", "206", "306", "308", "208", "3008", "508", "RCZ"],
  "Plymouth": ["Barracuda", "Road Runner", "GTX", "Superbird", "Duster", "Fury", "Prowler", "Voyager"],
  "Pontiac": ["GTO", "Firebird/Trans Am", "Fiero", "Bonneville", "Grand Prix", "Solstice", "Aztek", "LeMans", "Catalina", "Sunfire"],
  "Porsche": ["911", "Cayenne", "Boxster", "Cayman", "918 Spyder", "Carrera GT", "356", "Taycan", "Panamera", "959"],
  "Renault": ["5", "Clio", "Megane", "Espace", "4", "Twingo", "Captur", "Alpine A110", "Fuego", "Dauphine"],
  "Rolls-Royce": ["Phantom", "Ghost", "Cullinan", "Wraith", "Silver Shadow", "Silver Ghost", "Dawn", "Corniche", "Silver Seraph", "Silver Spirit"],
  "Rover": ["P5/P6", "75", "SD1", "200 Series", "800 Series", "Metro", "Mini (Pre-Austin)", "Land Rover (original)"],
  "Royal Enfield": ["Bullet", "Classic", "Interceptor", "Continental GT", "Himalayan", "Meteor"],
  "Saab": ["900", "99", "9-3", "9-5", "Sonett", "96"],
  "Seat": ["Ibiza", "Leon", "Ateca", "Arona", "Toledo", "Marbella"],
  "Skoda": ["Octavia", "Fabia", "Superb", "Yeti", "Kodiaq", "Enyaq", "Favorit", "Felicia"],
  "Subaru": ["Impreza", "WRX", "Legacy", "Outback", "Forester", "BRZ", "SVX", "Justy", "Brat", "XT"],
  "Suzuki": ["Jimny", "Swift", "Vitara", "Samurai", "Cappuccino", "Ignis", "GSX-R750 (Motorcycle)", "Hayabusa (Motorcycle)", "Katana (Motorcycle)", "V-Strom (Motorcycle)"],
  "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Roadster", "Cybertruck"],
  "Toyota": ["Corolla", "Supra", "Land Cruiser", "Hilux", "Camry", "Prius", "RAV4", "Celica", "MR2", "2000GT"],
  "Triumph": ["Bonneville", "Spitfire", "TR6", "Stag", "Dolomite", "TR7", "GT6", "Speed Triple (Motorcycle)", "Daytona 675 (Motorcycle)", "Tiger (Motorcycle)"],
  "TVR": ["Griffith", "Chimaera", "Cerbera", "Tuscan", "Sagaris", "Wedge Series"],
  "Vauxhall": ["Cavalier", "Astra", "Corsa", "Insignia", "VXR8", "Viva", "Victor", "Chevette", "VX220", "Carlton"],
  "Volkswagen": ["Beetle", "Golf", "Transporter/Bus", "Passat", "Jetta", "GTI", "Polo", "Tiguan", "Karmann Ghia", "Scirocco"],
  "Volvo": ["240 Series", "850", "P1800", "XC90", "S60", "V70", "Amazon", "C30", "S90", "140 Series"],
  "Yamaha": ["YZF-R1", "VMAX", "XT500", "RD350LC", "MT-07/MT-09", "YZ series", "Ténéré 700", "FZR", "R6", "DT-1"]
};

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const make = searchParams.get('make');

  if (make) {
    const models = (vehicleData as any)[make] || [];
    return NextResponse.json({ models });
  }

  const makes = Object.keys(vehicleData);
  return NextResponse.json({ makes });
}
