
import { NextResponse } from 'next/server';

const vehicleData = {
  "Abarth": ["595 / 695", "124 Spider", "Punto Evo", "Grande Punto"],
  "AC": ["Cobra", "Ace", "Aceca", "3000ME", "Greyhound"],
  "Acura": ["NSX", "Integra", "Legend", "MDX", "RDX", "TLX"],
  "Adler": ["Trumpf", "Trumpf Junior", "Diplomat", "Favorit", "Standard 6", "2.5-litre"],
  "AEC": ["Regent", "Routemaster", "Reliance", "Matador", "Monarch", "Mammoth"],
  "Aermacchi": ["Ala d'Oro", "Ala Verde", "Ala Azzurra", "Chimera", "Harley-Davidson Sprint"],
  "Aermacchi Harley-Davidson": ["Sprint", "Ala d'Oro", "M-50", "SS-350"],
  "AJS": ["7R 'Boy Racer'", "Model D", "Porcupine (E90/E95)", "S3 V-twin", "Big Port", "Model 18"],
  "Albion": ["Victor", "Valkyrie", "Viking", "Valiant", "Clydesdale", "Nimbus"],
  "Alfa Romeo": ["Giulia", "Spider", "Stelvio", "GTV", "Alfasud", "156", "Giulietta", "8C Competizione", "Montreal", "33 Stradale"],
  "Allard": ["J2", "K1", "P1", "M-Type", "Palm Beach", "Safari"],
  "Alpine": ["A110", "A310", "A610", "GTA"],
  "Alpina": ["B7", "B10 Bi-Turbo", "B3", "D3", "Roadster S", "B5"],
  "Alvis": ["TD 21", "TE 21", "TF 21", "Speed 20", "Speed 25", "4.3 Litre", "Grey Lady"],
  "AM General": ["HMMWV (Humvee)", "MV-1"],
  "AMC": ["Javelin", "AMX", "Gremlin", "Pacer", "Eagle", "Hornet"],
  "Amilcar": ["CGS", "CGSS", "C6", "Compound", "Pégase"],
  "Ariel": ["Atom", "Nomad", "Ace (motorcycle)", "Square Four (motorcycle)"],
  "Armstrong Siddeley": ["Sapphire", "Star Sapphire", "Whitley", "Hurricane", "Lancaster", "Typhoon"],
  "Aston Martin": ["DB5", "Vantage", "DB9", "DBS", "DB11", "Vanquish", "DBX", "Lagonda", "Valkyrie", "One-77"],
  "Auburn": ["851 Speedster", "6-51", "8-90", "12-160", "8-115"],
  "Audi": ["Quattro", "A4", "A6", "TT", "R8", "A3", "Q7", "Q5", "RS2 Avant", "e-tron"],
  "Austin": ["Mini", "Seven", "A30/A35", "Allegro", "Metro", "Princess", "Ambassador", "Cambridge", "Westminster", "1100/1300"],
  "Austin-Healey": ["3000", "100", "Sprite", "100-6"],
  "Autobianchi": ["A112", "Bianchina", "Y10", "Stellina", "Primula"],
  "Bedford": ["CA", "CF", "TK", "HA", "Rascal", "OB"],
  "Benelli": ["Sei (750/900)", "Tornado Tre 900", "TNT 1130", "Leoncino", "TRK 502", "491"],
  "Bentley": ["Continental GT", "Mulsanne", "Bentayga", "Arnage", "Flying Spur", "Blower Bentley", "R-Type Continental", "Brooklands", "Azure", "Turbo R"],
  "Berkeley": ["SA322", "T60", "B95", "Bandit", "QB"],
  "Bianchi": ["S9", "11F", "Tonale", "Freccia Celeste (bicycle)", "Aquilotto (moped)"],
  "Bizzarrini": ["5300 GT Strada", "P538", "GTS 4.1 V", "Manta (Concept)"],
  "BMW": ["3 Series", "5 Series", "M3", "M5", "X5", "2002", "Z3/Z4", "i8", "7 Series", "E9 CSL"],
  "Bond": ["Bug", "Minicar", "Equipe GT", "Ranger"],
  "Borgward": ["Isabella", "P100", "Hansa 1500", "Arabella", "B 2000"],
  "Bristol": ["400", "401", "405", "Blenheim", "Fighter", "Britannia"],
  "Brough-Superior": ["SS100", "SS80", "Pendine", "11.50"],
  "BSA": ["Gold Star", "Bantam", "A65", "Rocket 3", "M20"],
  "Bugatti": ["Veyron", "Chiron", "Type 57 Atlantic", "Type 35", "EB110", "Divo", "Centodieci", "La Voiture Noire"],
  "Buick": ["Riviera", "Regal", "Skylark", "Roadmaster", "GSX", "LeSabre", "Century", "Electra 225"],
  "Bultaco": ["Sherpa T", "Pursang", "Metralla", "TSS", "Matador", "Alpina"],
  "Cadillac": ["Eldorado", "Escalade", "DeVille", "CTS-V", "Series 62", "Fleetwood", "CT5-V Blackwing", "Allanté", "Seville", "Sixteen"],
  "Caterham": ["Seven", "21", "SP/300.R"],
  "Chenard - Walcker": ["Tank", "Aigle", "Y8", "1500", "Fregate"],
  "Chevrolet": ["Corvette", "Camaro", "Silverado", "Impala", "Bel Air", "Suburban", "Chevelle", "Tahoe", "Volt", "Monte Carlo"],
  "Chrysler": ["300", "Voyager / Town & Country", "New Yorker", "PT Cruiser", "Viper (under Dodge initially)", "Crossfire", "LeBaron", "Imperial"],
  "Citroen": ["DS", "2CV", "CX", "SM", "BX", "XM", "C4 Cactus", "GS", "Traction Avant", "HY Van"],
  "Commer": ["Superpoise", "Cob", "BF", "Walk-Thru", "Express", "TS3"],
  "Cord": ["810/812", "L-29", "E-1"],
  "Crossley": ["20/25", "Regis", "25/30 hp", "Ten"],
  "CZ": ["175", "250 Enduro", "380", "477"],
  "Dacia": ["Duster", "Sandero", "Logan", "Spring"],
  "Daf": ["600", "33", "44", "55", "66"],
  "Daihatsu": ["Copen", "Charade", "Terios", "Fourtrak", "Materia"],
  "Daimler": ["SP250 \"Dart\"", "Double Six", "Sovereign", "DS420 Limousine", "Conquest"],
  "Darracq": ["V8", "Flying Fifteen", "20/28hp", "12hp"],
  "Datsun": ["240Z", "510", "Bluebird", "Cherry", "Sunny", "120Y"],
  "De Dion Bouton": ["Vis-à-Vis", "Type G", "Populaire", "V8"],
  "De Tomaso": ["Pantera", "Mangusta", "Guarà", "Longchamp", "Deauville", "Vallelunga"],
  "Delage": ["D8", "D6", "DI", "DMS", "D12"],
  "Delahaye": ["135", "175", "235", "VLR"],
  "DeLorean": ["DMC-12"],
  "Dennis": ["Dart", "Trident", "Javelin", "Falcon", "Loline", "Lancet"],
  "DKW": ["F89", "3=6", "Munga", "RT 125", "1000 Sp", "F102"],
  "Dodge": ["Charger", "Challenger", "Viper", "Ram", "Durango", "Caravan", "Dart", "Coronet", "Daytona", "Omni"],
  "Ducati": ["Monster", "916", "Panigale", "Scrambler", "Multistrada", "Diavel", "Hypermotard", "SuperSport", "750 Imola Desmo", "851"],
  "Edsel": ["Pacer", "Ranger", "Corsair", "Citation", "Villager", "Bermuda"],
  "Elva": ["Courier", "MkVI", "MkVII", "160"],
  "ERF": ["EC", "LV", "KV", "A-series", "B-series", "C-series"],
  "Excalibur": ["Series I Roadster", "Series II Phaeton", "Series III", "Series IV", "Series V", "Cobra"],
  "Facel Vega": ["HK500", "Facel II", "Excellence", "Facellia"],
  "Fantic": ["Caballero", "Issimo", "Koala", "Chopper 125"],
  "Ferrari": ["F40", "Testarossa", "250 GTO", "LaFerrari", "Enzo", "Dino 246 GT", "458 Italia", "F355", "Daytona", "288 GTO"],
  "Fiat": ["500", "Panda", "Uno", "124 Spider", "Punto", "Multipla", "Tipo", "X1/9", "126", "127"],
  "FN": ["1300", "M70", "M13", "4-Cylinder car"],
  "Ford": ["Mustang", "F-150", "Model T", "GT/GT40", "Focus", "Fiesta", "Explorer", "Bronco", "Thunderbird", "Escort"],
  "Frazer Nash": ["Le Mans Replica", "Mille Miglia", "Targa Florio", "Sebring", "Falcon", "Fast Tourer"],
  "Gardner Douglas": ["GD427", "T70"],
  "Garelli": ["Mosquito", "Velo", "Katia", "Tiger Cross", "Rekord"],
  "Gilbern": ["GT", "Genie", "Invader"],
  "Gilera": ["Saturno", "500 LTE", "Nexus", "Runner", "Nordwest", "CX125"],
  "Ginetta": ["G4", "G12", "G15", "G40", "G55"],
  "GMC": ["Sierra", "Yukon", "Suburban", "Jimmy", "Syclone", "Typhoon", "Canyon", "Acadia"],
  "Gordon Keeble": ["GK1"],
  "Greeves": ["Silverstone", "Challenger", "Scottish", "Hawkstone", "Pathfinder", "Essex"],
  "Harley-Davidson": ["Sportster", "Fat Boy", "Electra Glide", "Softail", "Road King", "Dyna Wide Glide", "V-Rod", "Knucklehead", "Panhead", "Shovelhead"],
  "Healey": ["Silverstone", "Elliott", "Westland", "Tickford"],
  "Heinkel": ["Kabine", "Tourist"],
  "Hillman": ["Imp", "Avenger", "Hunter", "Minx"],
  "Hispano Suiza": ["H6", "J12", "Alfonso XIII", "K6", "Dubonnet Xenia"],
  "Honda": ["Civic", "Accord", "NSX", "CR-V", "S2000", "Prelude", "Integra", "CB750 (Motorcycle)", "Super Cub (Motorcycle)", "Gold Wing (Motorcycle)"],
  "Horch": ["853", "8", "930V", "P240"],
  "Hotchkiss": ["AM2", "Anjou", "Grégoire", "686", "M201 (Jeep)"],
  "HRG": ["1500", "1100", "Airline Coupe", "Le Mans"],
  "Hudson": ["Hornet", "Commodore", "Terraplane", "Super Six"],
  "Humber": ["Sceptre", "Super Snipe", "Hawk", "Imperial", "Pullman", "8"],
  "Husqvarna": ["Vitpilen", "Svartpilen", "701 Enduro", "TE 300i", "Nuda 900", "Silverpilen"],
  "Hyundai": ["i30", "Tucson", "Santa Fe", "Genesis Coupe", "i10", "i20", "Kona", "Ioniq 5"],
  "Indian": ["Chief", "Scout", "FTR", "Chieftain", "Springfield", "Roadmaster"],
  "Infiniti": ["Q50", "G35/G37", "QX80", "FX35/FX50", "QX60"],
  "Innocenti": ["Mini", "950 Spider", "Lambro", "IM3", "Regent", "De Tomaso"],
  "Invicta": ["S-Type", "Black Prince", "4½ Litre", "S1"],
  "Iso": ["Grifo", "Rivolta IR 300", "Lele", "Fidia", "Isetta"],
  "Isuzu": ["Trooper", "D-Max", "Piazza", "Vehicross", "Bellett"],
  "Itala": ["35/45hp \"Pekin-Paris\""],
  "Jaguar": ["E-Type", "XJ", "F-Type", "XKSS/D-Type", "Mark II", "XJ220", "F-Pace", "XF", "XK8/XKR", "I-Pace"],
  "Jeep": ["Wrangler", "Cherokee/Grand Cherokee", "Willys MB", "Gladiator", "Wagoneer", "Compass", "Renegade", "Commander"],
  "Jensen": ["Interceptor", "Healey", "541R", "CV8"],
  "Jowett": ["Javelin", "Jupiter", "Bradford", "Kestrel"],
  "Kawasaki": ["Ninja", "Z1", "H2", "Vulcan", "KLR650", "Versys", "KX Series", "Concours"],
  "Kia": ["Sportage", "Sorento", "Stinger", "Ceed", "Telluride", "EV6", "Soul", "Rio"],
  "Lada": ["Niva", "Riva/VAZ-2105", "Samara", "Classic/VAZ-2101"],
  "Lagonda": ["M45", "V12", "LG6", "2.6-Litre", "3-Litre", "Rapide"],
  "Lamborghini": ["Countach", "Miura", "Diablo", "Aventador", "Huracán", "Gallardo", "Murciélago", "Urus", "LM002", "Veneno"],
  "Lancia": ["Stratos", "Delta", "Fulvia", "Aurelia", "Beta", "Thema", "037 Stradale", "Flaminia", "Appia", "Gamma"],
  "Land Rover": ["Defender", "Range Rover", "Discovery", "Range Rover Sport", "Freelander", "Evoque", "Velar", "Series I/II/III"],
  "Laverda": ["Jota", "750 SFC", "3C", "Ghost", "RGS 1000", "750 SF"],
  "Lea Francis": ["Hyper", "14hp Sports", "2½ Litre Sports", "Ace of Spades"],
  "Lexus": ["LS 400", "LFA", "IS", "RX", "GS", "ES", "SC 400", "GX", "LX", "LC 500"],
  "Leyland": ["1500", "Marina", "P76", "Princess", "Sherpa", "National (bus)"],
  "Lincoln": ["Continental", "Navigator", "Town Car", "Mark Series", "Aviator", "Zephyr"],
  "Lister": ["Knobbly", "Storm", "Costin"],
  "Lola": ["T70", "T90", "B2K/10", "T290", "T332"],
  "Lotus": ["Elan", "Esprit", "Elise", "Exige", "Evora", "Europa", "Elite", "Emira", "Carlton", "Evija"],
  "Marcos": ["GT", "Mantis", "Mantara", "Mini Marcos", "LM600"],
  "Maserati": ["Ghibli", "Quattroporte", "GranTurismo", "MC20", "3500 GT", "Merak", "Bora", "Levante", "Shamal", "Biturbo"],
  "Matchless": ["G80", "G50", "G12", "Silver Hawk", "Silver Arrow"],
  "Matra": ["Djet", "530", "Bagheera", "Murena", "Rancho"],
  "Mazda": ["MX-5/Miata", "RX-7", "RX-8", "3", "6", "CX-5", "Cosmo", "323F", "CX-30", "MX-30"],
  "McLaren": ["F1", "P1", "720S", "Senna", "650S", "570S", "Artura", "MP4-12C", "GT", "Speedtail"],
  "Mercedes-Benz": ["300 SL", "S-Class", "E-Class", "G-Class", "C-Class", "SL-Class", "AMG GT", "CLK GTR", "SLS AMG", "190E"],
  "Messerschmitt": ["KR175", "KR200", "TG500 Tiger"],
  "MG": ["MGB", "Midget", "MGA", "TC/TD/TF", "F/TF", "ZS", "HS", "Metro", "Maestro", "Montego"],
  "Mini": ["Cooper (Classic)", "Cooper (BMW)", "Countryman", "Clubman", "John Cooper Works", "Moke"],
  "Minerva": ["AC", "AK", "AL", "M4"],
  "Mitsubishi": ["Lancer Evolution", "Pajero/Shogun", "GTO/3000GT", "Eclipse", "Galant", "Colt", "Outlander", "Starion", "i-MiEV", "Delica"],
  "Montesa": ["Cota", "Impala", "Cappra", "Enduro", "Brien"],
  "Morgan": ["Plus 4", "Plus 8", "3-Wheeler", "Aero 8", "4/4", "Roadster"],
  "Morris": ["Minor", "Oxford", "Eight", "Marina", "Ital", "Cowley"],
  "Moto Guzzi": ["V7", "Le Mans", "California", "Griso", "Norge", "Stelvio", "Daytona"],
  "Moto Morini": ["3½", "Corsaro", "Kanguro", "Excalibur", "Dart", "Seiemmezzo"],
  "Motobecane": ["Mobylette", "AV88", "D45", "350"],
  "MV Agusta": ["F4", "Brutale", "750 Sport America", "Superveloce", "Turismo Veloce", "Dragster"],
  "Nissan": ["GT-R", "Z-Series (Fairlady)", "Skyline", "Patrol", "Qashqai", "Juke", "Micra", "Titan", "Leaf", "Silvia/200SX"],
  "Noble": ["M600", "M12", "M400"],
  "Norton": ["Commando", "Manx", "Dominator", "International", "V4SV", "Atlas"],
  "NSU": ["Ro 80", "Prinz", "Sport Prinz", "Wankel Spider", "Quickly (Moped)", "Max"],
  "Oldsmobile": ["Cutlass", "442", "88", "Toronado", "Starfire", "Aurora"],
  "OM": ["469", "Taurus", "Lupetto", "Leoncino"],
  "Opel": ["Manta", "Kadett", "Corsa", "Astra", "Vectra", "Insignia", "GT", "Ascona", "Calibra", "Rekord"],
  "Ossa": ["MAR", "Phantom", "Explorer", "Yankee 500"],
  "Packard": ["Twelve", "Twin Six", "Caribbean", "Clipper", "Hawk"],
  "Pagani": ["Zonda", "Huayra"],
  "Panhard": ["24", "Dyna Z", "PL 17", "CD", "Dynamic", "Levassor"],
  "Panther": ["Kallista", "Lima", "De Ville", "J72", "Rio", "Solo"],
  "Peerless": ["V8", "GT"],
  "Peugeot": ["205", "405", "504", "206", "306", "308", "208", "3008", "508", "RCZ"],
  "Pierce-Arrow": ["Silver Arrow", "Model 66", "Model 48", "Arrow"],
  "Plymouth": ["Barracuda", "Road Runner", "GTX", "Superbird", "Duster", "Fury", "Prowler", "Voyager"],
  "Pontiac": ["GTO", "Firebird/Trans Am", "Fiero", "Bonneville", "Grand Prix", "Solstice", "Aztek", "LeMans", "Catalina", "Sunfire"],
  "Porsche": ["911", "Cayenne", "Boxster", "Cayman", "918 Spyder", "Carrera GT", "356", "Taycan", "Panamera", "959"],
  "Reliant": ["Scimitar GTE", "Robin", "Regal", "Sabre", "Kitten", "Bond Bug"],
  "Renault": ["5", "Clio", "Megane", "Espace", "4", "Twingo", "Captur", "Alpine A110", "Fuego", "Dauphine"],
  "Riley": ["RMA/RMB", "Pathfinder", "Elf", "Kestrel", "Nine", "Gamecock"],
  "Rolls-Royce": ["Phantom", "Ghost", "Cullinan", "Wraith", "Silver Shadow", "Silver Ghost", "Dawn", "Corniche", "Silver Seraph", "Silver Spirit"],
  "Rosengart": ["LR2", "LR4", "Supertraction"],
  "Rover": ["P5/P6", "75", "SD1", "200 Series", "800 Series", "Metro", "Mini (Pre-Austin)", "Land Rover (original)"],
  "Royal Enfield": ["Bullet", "Classic", "Interceptor", "Continental GT", "Himalayan", "Meteor"],
  "Rudge": ["Ulster", "Multi", "Special"],
  "Saab": ["900", "99", "9-3", "9-5", "Sonett", "96"],
  "Salmson": ["S4", "G72", "2300S"],
  "Seat": ["Ibiza", "Leon", "Ateca", "Arona", "Toledo", "Marbella"],
  "Simca": ["1000", "1100", "Aronde", "Vedette", "1300/1500", "1200S"],
  "Singer": ["Nine", "Gazelle", "Vogue", "Le Mans", "Hunter", "SM1500"],
  "Skoda": ["Octavia", "Fabia", "Superb", "Yeti", "Kodiaq", "Enyaq", "Favorit", "Felicia"],
  "Standard": ["Eight", "Ten", "Vanguard", "Flying Eight", "Pennant", "Avon"],
  "Studebaker": ["Avanti", "Champion", "President", "Hawk", "Lark", "Golden Hawk"],
  "Stutz": ["Bearcat", "Blackhawk", "Vertical Eight", "DV-32"],
  "Subaru": ["Impreza", "WRX", "Legacy", "Outback", "Forester", "BRZ", "SVX", "Justy", "Brat", "XT"],
  "Sunbeam": ["Tiger", "Alpine", "Rapier", "Talbot 90", "S7/S8 (Motorcycle)", "3-Litre"],
  "Suzuki": ["Jimny", "Swift", "Vitara", "Samurai", "Cappuccino", "Ignis", "GSX-R750 (Motorcycle)", "Hayabusa (Motorcycle)", "Katana (Motorcycle)", "V-Strom (Motorcycle)"],
  "Talbot": ["105", "Lago T150C SS", "Sunbeam", "Samba", "Horizon", "Matra Rancho"],
  "Talbot Lago": ["T150C SS", "T26C", "Grand Sport"],
  "Terrot": ["100cc", "HSSE", "BMA", "Magnat-Debon"],
  "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Roadster", "Cybertruck"],
  "Toyota": ["Corolla", "Supra", "Land Cruiser", "Hilux", "Camry", "Prius", "RAV4", "Celica", "MR2", "2000GT"],
  "Triumph": ["Bonneville", "Spitfire", "TR6", "Stag", "Dolomite", "TR7", "GT6", "Speed Triple (Motorcycle)", "Daytona 675 (Motorcycle)", "Tiger (Motorcycle)"],
  "TVR": ["Griffith", "Chimaera", "Cerbera", "Tuscan", "Sagaris", "Wedge Series"],
  "Vauxhall": ["Cavalier", "Astra", "Corsa", "Insignia", "VXR8", "Viva", "Victor", "Chevette", "VX220", "Carlton"],
  "Velocette": ["Thruxton", "KSS", "Viper", "Venom", "MOV", "GTP"],
  "Vincent": ["Black Shadow", "Black Lightning", "Rapide", "Comet", "Grey Flash", "Meteor"],
  "Volkswagen": ["Beetle", "Golf", "Transporter/Bus", "Passat", "Jetta", "GTI", "Polo", "Tiguan", "Karmann Ghia", "Scirocco"],
  "Volvo": ["240 Series", "850", "P1800", "XC90", "S60", "V70", "Amazon", "C30", "S90", "140 Series"],
  "Wartburg": ["353", "311", "1.3"],
  "Willys": ["Jeep Station Wagon", "Aero", "Jeepster", "Knight", "Overland", "MB"],
  "Wolseley": ["Hornet", "1500", "4/44", "6/80", "18/85", "Wasp"],
  "Yamaha": ["YZF-R1", "VMAX", "XT500", "RD350LC", "MT-07/MT-09", "YZ series", "Ténéré 700", "FZR", "R6", "DT-1"],
  "Zundapp": ["KS750", "Bella", "KS601", "Janus", "DB200", "Elastic"]
};

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const make = searchParams.get('make');

  if (make) {
    const models = (vehicleData as any)[make] || [];
    return NextResponse.json({ models });
  }

  const makes = Object.keys(vehicleData).sort();
  return NextResponse.json({ makes });
}

    
    
